### ISSUE TITLE
你好我打包了一下，看看行不

### ISSUE THREAD

**Issue by kafuuchino-s** [Blacklyy/autoMedic#1]
我这里可以直接运行，但我不太确定没有编译环境的可以直接运行吗？
[新建文件夹.zip](https://github.com/Blacklyy/autoMedic/files/8693078/default.zip)

**Comment by Blacklyy** [comment]
是用pyinstaller打包的吗，我本来也想打包，但是打包过程中报错了，所以暂时发的还是源代码。
如果正常打包的话应该是可以在没有python环境的电脑上运行的。

**Comment by kafuuchino-s** [comment]
是的，我因为手上的电脑都有python环境，不好测试
我想着python配置起来对于大部分没基础的也有点麻烦

**Comment by Blacklyy** [comment]
你的打包 我目前在自己电脑上测试是可以运行的。我会在我在豆瓣上发的帖子 https://www.douban.com/group/topic/266783421/#sep?_i=2537763d1H-fN9 里面附上你的下载链接。你也可以自己发帖子进行宣传，你看可以吗。

**Comment by kafuuchino-s** [comment]
你发吧，我希望可以帮助到你，我也想着selenium来着的，只不过我用的chrome

**Comment by Blacklyy** [comment]
好的，那我在帖子上方附上你的下载链接。
本来是计划用chrome的，但是想到edge每个windows用户都肯定有，所以选择了edge。
